[tools]
go = "1.24.5"
node = "24.4.0"
pnpm = "latest"

[tasks]
# 開発用コマンド
dev = "pnpm dev"
start = "pnpm dev"

# ビルド関連
build = "pnpm build"
build-all = "pnpm build:all"
rebuild = "pnpm rebuild"
clean = "pnpm clean"

# 個別パッケージビルド
build-components = "pnpm components:build"
build-wasm = "pnpm wasm:build"
build-web = "pnpm web:build"

# 開発用（個別パッケージ）
dev-components = "pnpm components:dev"
dev-wasm = "pnpm wasm:dev"
dev-web = "pnpm web:dev"

# テスト関連
test = "pnpm test"
test-all = "pnpm test:all"
test-components = "pnpm components:test"
test-wasm = "pnpm wasm:test"
test-web = "pnpm web:test"

# 型チェック・リント
typecheck = "pnpm typecheck"
lint = "pnpm lint"
lint-fix = "pnpm lint:fix"
format = "pnpm format:fix"
format-check = "pnpm format:check"
check = "pnpm check"
check-fix = "pnpm check:fix"

# プレビュー
preview = "pnpm web:preview"

# 依存関係管理
install = "pnpm install"
update = "pnpm update"

# CI用
ci-install = "pnpm install --frozen-lockfile"
ci-build = "pnpm build:all"
ci-test = "pnpm test:all"
ci-check = "pnpm typecheck && pnpm lint"

# GitHub Actions用
gh-setup = "mise install && pnpm install"
gh-test = "pnpm --filter @boid-wasm-sim/wasm test && pnpm --filter @boid-wasm-sim/hooks test && pnpm --filter @boid-wasm-sim/web test"
gh-build = "pnpm --filter @boid-wasm-sim/wasm build && pnpm --filter @boid-wasm-sim/hooks build && pnpm --filter @boid-wasm-sim/components build && pnpm --filter @boid-wasm-sim/web build"
gh-deploy = "cd web/main && VITE_BASE_PATH=/boid-wasm-sim/ pnpm build"

# セキュリティチェック
security-audit = "pnpm audit --audit-level moderate"
security-check = "pnpm audit"