packages:
  - 'web/main'
  - 'web/components'
  - 'web/hooks'
  - 'wasm'

catalog:
  "vitest": "4.1.10"
  "typescript": "7.0.2"
  "vite": "8.2.0"

onlyBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080
